name: Release Tagged Version

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - run: |
          sudo apt-get update
          sudo apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev libpulse-dev -y
              
      - name: Setup Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'
      
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7
      - run: |
          poetry install --no-root
          poetry build
      
      - name: "Release Tagged Version"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            dist/**